### ISSUE TITLE
test_fft2.test_parseval fails on macbook 

### ISSUE THREAD

**Issue by rabernat** [rabernat/pyqg#4]
This test failed on my macbook but worked fine on my linux workstation. I think it is a precision issue.

```
======================================================================
FAIL: test_fft2.test_parseval
Make sure 2D fft from QGModel satisfy Parseval's relation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rpa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/rpa/RND/Public/pyqg/pyqg/tests/test_fft2.py", line 28, in test_parseval
    assert error<rtol, " *** QGModel FFT2 does not satisfy Parseval's relation "
AssertionError:  *** QGModel FFT2 does not satisfy Parseval's relation 
-------------------- >> begin captured stdout << ---------------------
Variance from spectrum: 1.0320939902371178
Variance in physical space: 1.0320939902371151
error = 0.0000000000000026
```

**Comment by crocha700** [comment]
This works on my MacPro.

**Comment by crocha700** [comment]
So, this might indeed be a precision issue. One thing to notice is that while we can compute the DFT to machine double precision, we may loose a bit of accuracy when we square the absolute value of the Fourier coefs.  So perhaps 1.e-15 for error tolerance is too restrictive ? (1.e-14 would pass the test above...)

**Comment by rabernat** [comment]
My macbook is 64-bit though (Intel Core i7), and so is my python (Canopy). My numpy version is 1.8.1. So shouldn't it work the same? I am ok with changing it rtol to 1e-14, but it would be nice to understand the source of the difference.

**Comment by MFJansen** [comment]
Are you guys using the same fft? I haven't gone through the new code in detail, but it looks like it may be using different libraries depending on what's available.

**Comment by crocha700** [comment]
Yes, much better to understand the source of error first.

Here it the test passes for both ffts (set fftw=true if you have it installed...). This test passes both in my laptop and on our linux server.  Both my Mac Pro and the server are 64-bit with 64-bit python (anaconda), numpy version 1.9.2.

**Comment by MFJansen** [comment]
Fails for me:
Variance from spectrum: 1.0143052814763658
Variance in physical space: 1.0143052814763691
error = 0.0000000000000033
(very recent canopy python installation on 2015 iMac)

**Comment by MFJansen** [comment]
I actually think this error is probably ok, given that it's in the 16th digit (if I'm not misinformed you expect at least 15 significant digits in double precision). I'm still a bit surprised to see that the results are platform dependent, but I'm never quite sure when to expect exact matches and when not to.
