### ISSUE TITLE
Shape returned by rfft2 not consistent

### ISSUE THREAD

**Issue by rabernat** [rabernat/pyqg#5]
This is a really strange error.

In the process of investigating the origin of the test mismatches, I tried to run the current master branch tests on the mac pro that Malte and I were using last summer. The test_twolayer_qg.test_the_model test failed with the following error.

```
ERROR: test_twolayer_qg.test_the_model
Make sure the results are correct within relative tolerance rtol.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rpa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/rpa/RND/Public/pyqg/pyqg/tests/test_twolayer_qg.py", line 35, in test_the_model
    m.run()
  File "/Users/rpa/RND/Public/pyqg/pyqg/qg_model.py", line 249, in run
    self._step_forward()
  File "/Users/rpa/RND/Public/pyqg/pyqg/qg_model.py", line 262, in _step_forward
    self.ph1, self.ph2 = self.invph(self.qh1, self.qh2)
  File "/Users/rpa/RND/Public/pyqg/pyqg/qg_model.py", line 230, in invph
    ph1 = self.a11*zh1 + self.a12*zh2
ValueError: operands could not be broadcast together with shapes (32,17) (32,32) 
```

It turns out that this is due to np.fft.rfft2 returning different shapes on the two different machines. On my laptop (where the test succeeds) I get
```python
>>> np.fft.rfft2(np.zeros((16,16))).shape
(16, 9)
```
This result makes sense, since the point of rfft is not to compute the redundant fourier coefficients. On this machine, I have numpy 1.8.1, Canopy 64 bit python 2.7.6.
 
However, on the mac pro, I get
```python
>>> np.fft.rfft2(np.zeros((16,16))).shape
(16, 16)
```
which of course breaks the whole model. This machine has numpy 1.8.1, Canopy 64 bit python 2.7.3.

**Comment by crocha700** [comment]
This is pretty wild. Here both machines (mac and linux) with anaconda 64-bit python 2.7.9, numpy 1.9.2.

I'd test to see if the rfft2 is returning something that is symmetric/redundant (that is, is the output of rfft2 the same of fft2?). You could just use a slanted plane wave or a gaussian field, and plot the absolute value of the fft. If that's the case, we may report this bug elsewhere.

**Comment by crocha700** [comment]
This is pretty wild. Here I get the correct shape in both machines (mac and linux) with anaconda 64-bit python 2.7.9, numpy 1.9.2.

I'd test to see if the rfft2 is returning the same output of fft2. You could just use a slanted plane wave or a gaussian, and plot the absolute value of the fft. If that's the case, we may report this bug elsewhere.

**Comment by rabernat** [comment]
Yes, rfft2 is returning the exact same input as fft2. This passes:
```python
np.testing.assert_allclose(np.fft.fftn(a), np.fft.rfftn(a))
```

This is using a canopy MKL library.
```python
>>> np.fft.rfft2
<function fastnumpy.mklfft.rfft2>
```

**Comment by crocha700** [comment]
What if you set np.use_fastnumpy = False ? Does it use  numpy.fft.fftpack.rfft2?

**Comment by MFJansen** [comment]
The current master commit fails on my Laptop with the same problem. I'm also using MKL. I somehow am unable to turn off the use of MKL on my laptop. Setting "np.use_fastnumpy = False" does not seem to change anything. ( b.t.w. the opposite is true on my desktop, even though the MKL libraries appear to be installed and linked, I don't get numpy to actually use them. I remember having this problem when I first tried to get MKL running on my laptop, and honestly I have no idea what made it work in the end... If anybody has advice on that I would appreciate it - but maybe email since this is somewhat off topic)

**Comment by crocha700** [comment]
Guys, I found  a [thread](https://github.com/ContinuumIO/anaconda-issues/issues/176) that was open in "Anaconda-issues" last September. People reported this bug with mkl real fft. Apparently there are other bugs too!

Here it works in my anaconda installation using mklfft with fftpack:

<pre><code>
In [2]: np.fft.rfft2
Out[2]:  function mklfft.fftpack.rfft2
In [5]: np.fft.rfft2(np.zeros((16,16))).shape
Out[5]: (16, 9)
</code></code>

**Comment by MFJansen** [comment]
Yeah, something is a bit messed up with the MKL rfft - though actually rfft2 for a real array does just the same as fft2 (and thus preserves the format) - the problem then is irfft though. So ifft2(rfft2(x)) does return x, but irfft2(rfft2(x)) gets messed up. I also find rfft2 to actually be slightly slower than fft2 though (see below).

timeit.timeit('numpy.fft.fft2(numpy.ones((128,128)))',setup='import numpy',number=10000)
Out[72]: 2.387770891189575

timeit.timeit('numpy.fft.rfft2(numpy.ones((128,128)))',setup='import numpy',number=10000)
Out[73]: 2.641757011413574

**Comment by crocha700** [comment]
Malte, in which machine did you test this? On my Mac Pro with Anaconda (64-bit) rfft2 is about twice faster, though both are much slower than in your computer !

<pre><code>
In [1]: import time
In [2]: timeit.timeit('numpy.fft.fft2(numpy.ones((128,128)))',setup='import numpy',number=10000)
Out[2]: 11.379649877548218
In [3]: timeit.timeit('numpy.fft.rfft2(numpy.ones((128,128)))',setup='import numpy',number=10000)
Out[3]: 5.282595872879028
</code></pre>

**Comment by MFJansen** [comment]
This was a 2010 MacBook Pro with i7 dual core at 2.7 GHZ, using Canopy with MKL.

Your results seem oddly slow. This is what I'm getting on my iMac with i7 quad core at 4GHz WITHOUT MKL (because I can't get it to use MKL):

numpy.fft.rfft2
Out[10]: <function numpy.fft.fftpack.rfft2>

timeit.timeit('numpy.fft.fft2(numpy.ones((128,128)))',setup='import numpy',number=10000)
Out[11]: 2.633178949356079

timeit.timeit('numpy.fft.rfft2(numpy.ones((128,128)))',setup='import numpy',number=10000)
Out[12]: 1.6765720844268799

so without MKL rift is indeed significantly faster

**Comment by rabernat** [comment]
This is a problem with MKL. Now that we have switched to pyfftw, it is moot.
